### ISSUE TITLE
Invalid or Expired token; But it connects fine on the Chrome window

### ISSUE THREAD

**Issue by Goldenschmidt** [LegendPoet/SillyTavern-1.9.7-fix#4]
> **Warning**. Complete **all** the fields below. Otherwise, your bug report will be **ignored**!

**Have you searched for similar [bugs](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes. But none are of SillyTavern-fix, nor of recent days.

**Describe the bug**
Trying to connect to Poe through SillyTavern-fix, and ensuring that the API key is correct, gives me the error "Invalid or expired token".
However, the Chrome browser that opens does show Poe.com as open and ready for prompts. Checking the console, there appears to be an error. (See Screenshot below)

**To Reproduce**
1. Start SillyTavern
2. Paste in your API key from Poe.com into the text bar where you need to put in the key.
3. Click on 'Connect'
3. Wait a few seconds.

**Expected behavior**
Expected SillyTavern to connect and be ready to send and receive prompts.

**Screenshots**
![billede](https://github.com/LegendPoet/SillyTavern-fix/assets/23004163/ee91b71a-4428-4780-880a-05954a54cfbe)

**Logs**

'Providing the logs from the browser DevTools console (opened by pressing the F12 key) or SillyTavern command line window will be highly appreciated.' ← Don't know what this implies, but have the stuff from the command prompt:
>BOTNAME DURING INITIALIZING: gptforst
>DEBUG: Current page title: Poe - GPTforST
>Error [TypeError]: Cannot read properties of undefined (reading 'click')
    at evaluate (evaluate at PoeClient.getBotNames (C:\Users\####\Documents\AIStuff\SillyTavern-1.9.7-fix\src\poe-client.js:387:25), <anonymous>:12:20)
    at #evaluate (C:\Users\####\Documents\AIStuff\SillyTavern-1.9.7-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:254:55)
    at async ExecutionContext.evaluate (C:\Users\####\Documents\AIStuff\SillyTavern-1.9.7-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:151:16)
    at async PoeClient.getBotNames (C:\Users\####\Documents\AIStuff\SillyTavern-1.9.7-fix\src\poe-client.js:387:9)
    at async C:\Users\####\Documents\AIStuff\SillyTavern-1.9.7-fix\server.js:2929:20

**Desktop (please complete the following information):**
 - OS/Device: Windows 10
 - Environment: Local
 - Node.js version (if applicable): 18.17.1
 - Browser: Firefox
 - Generation API: Poe
 - Branch: Main
 - Model: GPTforST

**Comment by erebar** [comment]
It works when you download the source. The releases don't have the fix (I tested 1.9.7) and that has the same problem that you describe.

**Comment by LegendPoet** [comment]
Did you update your repository? From what I see, you have an older version of the integration.

**Comment by Goldenschmidt** [comment]
Just tried again with a completely clean pull of the Main branch.
It still gives me the error.

>BOTNAME DURING INITIALIZING: gptforst
Error [TypeError]: Cannot read properties of null (reading 'parentElement')
    at evaluate (evaluate at PoeClient.initializeDriver (D:\Users\####\Documents\AIstuff\SillyTavern-fix\src\poe-client.js:125:25), <anonymous>:2:22)
    at #evaluate (D:\Users\####\Documents\AIstuff\SillyTavern-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:229:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (D:\Users\####\Documents\AIstuff\SillyTavern-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:126:16)
    at async IsolatedWorld.evaluate (D:\Users\####\Documents\AIstuff\SillyTavern-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\IsolatedWorld.js:129:16)
    at async CdpFrame.evaluate (D:\Users\####\Documents\AIstuff\SillyTavern-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:370:20)
    at async CdpPage.evaluate (D:\Users\####\Documents\AIstuff\SillyTavern-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:872:20)
    at async PoeClient.initializeDriver (D:\Users\####\Documents\AIstuff\SillyTavern-fix\src\poe-client.js:125:9)
    at async getPoeClient (D:\Users\####\Documents\AIstuff\SillyTavern-fix\server.js:2613:39)
    at async D:\Users\####\Documents\AIstuff\SillyTavern-fix\server.js:2642:24
