### ISSUE TITLE
[BUG] Cannot read properties of null

### ISSUE THREAD

**Issue by LegionInstaller** [LegendPoet/SillyTavern-1.9.7-fix#6]
Error [TypeError]: Cannot read properties of null (reading 'parentElement')
    at evaluate (evaluate at PoeClient.initializeDriver (E:\WaifuAIGeneration\NoFriends\SillyTavern-1.8.4-fix\src\poe-client.js:125:25), <anonymous>:2:22)
    at #evaluate (E:\WaifuAIGeneration\NoFriends\SillyTavern-1.8.4-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:229:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (E:\WaifuAIGeneration\NoFriends\SillyTavern-1.8.4-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\ExecutionContext.js:126:16)
    at async IsolatedWorld.evaluate (E:\WaifuAIGeneration\NoFriends\SillyTavern-1.8.4-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\IsolatedWorld.js:129:16)
    at async CdpFrame.evaluate (E:\WaifuAIGeneration\NoFriends\SillyTavern-1.8.4-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Frame.js:370:20)
    at async CdpPage.evaluate (E:\WaifuAIGeneration\NoFriends\SillyTavern-1.8.4-fix\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:872:20)
    at async PoeClient.initializeDriver (E:\WaifuAIGeneration\NoFriends\SillyTavern-1.8.4-fix\src\poe-client.js:125:9)
    at async getPoeClient (E:\WaifuAIGeneration\NoFriends\SillyTavern-1.8.4-fix\server.js:2939:39)
    at async E:\WaifuAIGeneration\NoFriends\SillyTavern-1.8.4-fix\server.js:2968:24

**Comment by LegendPoet** [comment]
Errors were corrected. Update according to your version.

**Comment by LegionInstaller** [comment]
> Errors were corrected. Update according to your version.

Works, Thanks Man
